application: obulpathinew
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /academics.html
  static_files: academics.html
  upload: academics.html

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /Obulpathi.pdf
  static_files: Obulpathi.pdf
  upload: Obulpathi.pdf

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
     
- url: /.*
  static_files: index.html
  upload: index.html
