runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /assets
  static_dir: assets

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /Obulpathi.pdf
  static_files: Obulpathi.pdf
  upload: Obulpathi.pdf

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  static_files: index.html
  upload: index.html
